"""W3C PROV-DM Provenance Service for SPHEREx Odyssey (Phase 9).

Implements the W3C PROV-DM Core Data Model (https://www.w3.org/TR/prov-dm/)
for every measurement, derived quantity, and dataset flowing through the
backend. Each provenance block records:

  - prov:Entity    : the artifact (a measurement, a derived quantity, a record)
  - prov:Activity  : the process that produced it (a query, a derivation,
                     a calibration)
  - prov:Agent     : the entity responsible for the activity (a service,
                     a catalogue, a person)

Per W3C PROV-DM §5.5, every Entity must be derivable from an Activity that
itself was associated with an Agent. The Odyssey implementation uses a flat
serializable dict (matching the JSON-LD-friendly structure used by PROV-JSON
https://www.w3.org/Submission/prov-json/) so the same provenance block can
be exported as a PROV-JSON document for archival.

Phase 9 invariants enforced here:

  1. Asymmetric intervals (e.g. Bailer-Jones r_lo_geo, r_hi_geo) are
     preserved as separate lower/upper fields. They are NEVER collapsed to
     a symmetric ±sigma, which would erase genuine astrophysical asymmetry
     (Luri et al. 2018; Bailer-Jones et al. 2021).
  2. Every uncertainty field carries explicit units (mas, km/s, μJy, etc.).
     A bare float without units is a provenance violation.
  3. Every uncertainty is paired with `uncertainty_kind` ∈
     {"statistical", "systematic", "statistical+systematic", "posterior"}.
     Statistical-only is the default; systematic is rare and must be
     explicitly noted; posterior is reserved for catalogued posteriors
     (Bailer-Jones, distance posteriors, etc.).
  4. Provenance blocks are additive and immutable: once a block is attached
     to a measurement, the service refuses to overwrite it. Updates create
     a new block referencing the prior one via `wasRevisionOf`.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Set
from pydantic import BaseModel, Field, model_validator

log = logging.getLogger("provenance")


# W3C PROV-DM Activity / Agent / Entity role identifiers used by Odyssey.
PROV_ROLES = frozenset({
    "primary",           # dataset / agent is the primary source
    "derived",           # computed from one or more primary inputs
    "calibrated",        # post-pipeline calibration applied
    "reference",         # used as a cross-match reference
    "validation",        # used for QA / validation only
    "fallback",          # used only when primary was unavailable
})

UNCERTAINTY_KINDS = frozenset({
    "statistical",
    "systematic",
    "statistical+systematic",
    "posterior",          # credible interval from a Bayesian posterior
    "asymmetric",         # interval with non-Gaussian shape (e.g. r_lo ≠ r_hi)
})


class W3CProvEntity(BaseModel):
    """A W3C PROV-DM Entity (prov:Entity).

    The 'artifact' that was generated by an Activity. For a SPHEREx spectrum
    point this is the (wavelength, flux, flux_err) tuple; for a derived
    quantity like tangential_velocity this is the (pmra, pmdec, plx)-derived
    scalar with its propagated uncertainty.
    """
    entity_id: str
    entity_type: str  # e.g. "spexpi:spectrum_point", "gaia:astrometric_record", "bj:distance_posterior"
    label: Optional[str] = None
    attributes: Dict[str, Any] = Field(default_factory=dict)
    was_revision_of: Optional[str] = None  # PROV-DM prov:wasRevisionOf → prior entity_id


class W3CProvActivity(BaseModel):
    """A W3C PROV-DM Activity (prov:Activity).

    The process that generated one or more Entities. For an external query
    this is the HTTP call against IRSA / JPL / CDS / ESA; for a derivation
    this is the local computation (e.g. tangential velocity propagation).
    """
    activity_id: str
    activity_type: str  # e.g. "query:irsa_sia", "query:jpl_horizons", "derivation:bj_distance"
    started_at: Optional[str] = None
    ended_at: Optional[str] = None
    used: List[str] = Field(default_factory=list)  # entity_ids consumed
    attributes: Dict[str, Any] = Field(default_factory=dict)


class W3CProvAgent(BaseModel):
    """A W3C PROV-DM Agent (prov:Agent).

    The entity (service, catalogue, person) responsible for an Activity.
    """
    agent_id: str
    agent_type: str  # e.g. "service:irsa", "service:jpl_horizons", "catalog:gaia_dr3"
    label: Optional[str] = None
    attributes: Dict[str, Any] = Field(default_factory=dict)


class W3CProvBlock(BaseModel):
    """A complete W3C PROV-DM provenance bundle for a single artifact.

    Designed to be embedded inside other Pydantic models (SPHEREx measurements,
    derived kinematics, astrophysical properties, unified object payloads)
    without polluting the parent schema. The bundle includes all three PROV
    classes plus the PROV-DM 'wasAttributedTo' relationship implicit in the
    agent list.
    """
    bundle_id: str = Field(default_factory=lambda: f"prov:{uuid.uuid4()}")
    generated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    entities: List[W3CProvEntity] = Field(default_factory=list)
    activities: List[W3CProvActivity] = Field(default_factory=list)
    agents: List[W3CProvAgent] = Field(default_factory=list)
    primary_role: str = "primary"

    @model_validator(mode="after")
    def _require_prov_dm_minimum_classes(self) -> "W3CProvBlock":
        """Phase 12 hard validator: every W3CProvBlock must carry at least one
        entity, at least one activity, and at least one agent.

        W3C PROV-DM §5.5 requires that every entity be derivable from an
        activity associated with an agent. An empty bundle is the prologue
        to a provenance hole — refuse it at construction time.
        """
        if not self.entities:
            raise ValueError(
                "W3CProvBlock must contain at least one W3CProvEntity "
                "(W3C PROV-DM §5.5)"
            )
        if not self.activities:
            raise ValueError(
                "W3CProvBlock must contain at least one W3CProvActivity "
                "(W3C PROV-DM §5.5)"
            )
        if not self.agents:
            raise ValueError(
                "W3CProvBlock must contain at least one W3CProvAgent "
                "(W3C PROV-DM §5.5)"
            )
        if self.primary_role not in PROV_ROLES:
            raise ValueError(
                f"W3CProvBlock.primary_role={self.primary_role!r} is not "
                f"in {PROV_ROLES}"
            )
        return self

    def has_agent(self, agent_id: str) -> bool:
        return any(a.agent_id == agent_id for a in self.agents)

    def find_entity(self, entity_id: str) -> Optional[W3CProvEntity]:
        for e in self.entities:
            if e.entity_id == entity_id:
                return e
        return None


class Uncertainty(BaseModel):
    """Typed uncertainty value with units and provenance kind.

    Phase 9 invariant: every reported uncertainty carries explicit units and
    an uncertainty_kind. A bare `error: 0.05` without a `unit` field is a
    provenance violation — the units are part of the data, not metadata.

    For asymmetric posteriors (e.g. Bailer-Jones), use the dedicated
    `AsymmetricInterval` model below rather than collapsing to ±sigma.
    """
    value: Optional[float] = None
    unit: Optional[str] = None  # e.g. "mas", "km/s", "μJy", "K", "M_sun"
    uncertainty_kind: str = "statistical"
    provenance: Optional[W3CProvBlock] = None
    # Statistical confidence level when applicable (e.g. 0.68 for 1-sigma,
    # 0.95 for 2-sigma credible intervals). None means the source did not
    # specify — DO NOT fabricate one.
    confidence_level: Optional[float] = None
    # Reference to the source: bibcode, DOI, or upstream catalogue ID
    reference: Optional[str] = None

    @model_validator(mode="after")
    def _require_unit_and_kind_when_value_present(self) -> "Uncertainty":
        """Phase 12 hard validator: a non-None value MUST carry a unit AND
        a valid uncertainty_kind. None values are permitted (the measurement
        is absent) and skip the check."""
        if self.value is None:
            return self
        if not self.unit:
            raise ValueError(
                f"Uncertainty with value={self.value} must carry a non-empty "
                "unit (e.g. 'mas', 'km/s', 'uJy'). A bare float without units "
                "is a provenance violation."
            )
        if self.uncertainty_kind not in UNCERTAINTY_KINDS:
            raise ValueError(
                f"Uncertainty.uncertainty_kind={self.uncertainty_kind!r} is "
                f"not in {UNCERTAINTY_KINDS}"
            )
        return self

    def is_well_formed(self) -> bool:
        """Return True iff this uncertainty carries units and provenance kind."""
        if self.value is None:
            return True  # None uncertainty is permitted (measurement absent)
        return bool(self.unit) and self.uncertainty_kind in UNCERTAINTY_KINDS


class AsymmetricInterval(BaseModel):
    """Asymmetric uncertainty interval, preserving r_lo ≠ r_hi.

    Phase 9 invariant: asymmetric credible intervals must NEVER be collapsed
    to a symmetric ±sigma. For Bailer-Jones distances this means preserving
    r_lo_geo and r_hi_geo as separate fields. The midpoint r_med is a
    summary statistic and is NOT a substitute for the interval.
    """
    median: Optional[float] = None
    lower: Optional[float] = None
    upper: Optional[float] = None
    unit: Optional[str] = None
    uncertainty_kind: str = "posterior"
    confidence_level: Optional[float] = None  # e.g. 0.5 for the median-centered 50% interval
    reference: Optional[str] = None  # e.g. "Bailer-Jones et al. 2021, AJ 161, 147 (DOI: 10.3847/1538-3881/abd806)"
    provenance: Optional[W3CProvBlock] = None

    @model_validator(mode="after")
    def _enforce_interval_invariants(self) -> "AsymmetricInterval":
        """Phase 12 hard validators:

        1. lower ≤ median ≤ upper when all three are present.
        2. A non-None value must carry a unit and a valid uncertainty_kind.
        3. We reject the degenerate case where median == lower == upper
           (that would mean the asymmetric interval was silently collapsed
           to a scalar — Luri et al. 2018 forbids this).
        """
        if self.median is None:
            # No scalar value present → invariants are vacuous.
            return self
        if not self.unit:
            raise ValueError(
                f"AsymmetricInterval with median={self.median} must carry a "
                "non-empty unit."
            )
        if self.uncertainty_kind not in UNCERTAINTY_KINDS:
            raise ValueError(
                f"AsymmetricInterval.uncertainty_kind={self.uncertainty_kind!r} "
                f"is not in {UNCERTAINTY_KINDS}"
            )
        if self.lower is not None and self.upper is not None:
            if not (self.lower <= self.median <= self.upper):
                raise ValueError(
                    f"AsymmetricInterval violates lower <= median <= upper: "
                    f"lower={self.lower}, median={self.median}, upper={self.upper}"
                )
            if self.lower == self.median == self.upper:
                raise ValueError(
                    "AsymmetricInterval collapsed to a scalar "
                    "(lower == median == upper). Asymmetric posteriors must "
                    "preserve the asymmetric interval — Luri et al. 2018."
                )
        return self

    def is_well_formed(self) -> bool:
        if self.median is None:
            return True
        return bool(self.unit) and self.uncertainty_kind in UNCERTAINTY_KINDS

    def is_symmetric(self) -> bool:
        """Return True iff lower and upper are present and equal to within 1%."""
        if self.lower is None or self.upper is None or self.median is None:
            return False
        if self.median == 0:
            return abs(self.lower) < 1e-9 and abs(self.upper) < 1e-9
        lower_dev = abs(self.median - self.lower) / abs(self.median)
        upper_dev = abs(self.upper - self.median) / abs(self.median)
        return max(lower_dev, upper_dev) < 0.01


class ProvenanceService:
    """In-memory store of W3C PROV-DM bundles keyed by entity_id or unified object id.

    The service is intentionally simple — bundles are appended, never mutated.
    Each call to record() returns the bundle_id so the caller can reference it
    from a measurement, derived quantity, or unified object payload.

    For Phase 9 the service is in-memory. A future phase can swap the storage
    layer for SQLite or a PROV-JSON archival store without changing the call
    sites.
    """

    def __init__(self) -> None:
        self._bundles: Dict[str, W3CProvBlock] = {}
        self._by_object: Dict[str, List[str]] = {}  # unified object id → bundle_ids

    def record(
        self,
        *,
        entities: List[W3CProvEntity],
        activities: List[W3CProvActivity],
        agents: List[W3CProvAgent],
        unified_object_id: Optional[str] = None,
        primary_role: str = "primary",
    ) -> W3CProvBlock:
        """Record a new PROV-DM bundle. Returns the bundle."""
        bundle = W3CProvBlock(
            entities=entities,
            activities=activities,
            agents=agents,
            primary_role=primary_role,
        )
        self._bundles[bundle.bundle_id] = bundle
        if unified_object_id:
            self._by_object.setdefault(unified_object_id, []).append(bundle.bundle_id)
        log.debug(
            "Recorded PROV-DM bundle %s with %d entities, %d activities, %d agents",
            bundle.bundle_id,
            len(entities),
            len(activities),
            len(agents),
        )
        return bundle

    def get(self, bundle_id: str) -> Optional[W3CProvBlock]:
        return self._bundles.get(bundle_id)

    def for_object(self, unified_object_id: str) -> List[W3CProvBlock]:
        """Return all bundles recorded against a unified object id, in insertion order."""
        return [
            self._bundles[bid]
            for bid in self._by_object.get(unified_object_id, [])
            if bid in self._bundles
        ]

    def all_bundles(self) -> List[W3CProvBlock]:
        return list(self._bundles.values())


# Module-level singleton. Tests can reset() it between cases.
provenance_service = ProvenanceService()


# ── Convenience builders ─────────────────────────────────────────────────────
# These helpers produce well-formed W3C PROV-DM bundles for the common
# upstream sources. They keep the call sites in normalization.py legible while
# guaranteeing the required agents/activities are always recorded.


def make_irsa_query_provenance(
    *,
    collection: str,
    release: str,
    doi: str,
    queried_at: str,
    query_url: str,
    cone_search: str,
    product_count: int,
    entity_label: str,
    unified_object_id: Optional[str] = None,
) -> W3CProvBlock:
    """PROV-DM bundle for an IRSA SIA / TAP query."""
    e_query = W3CProvEntity(
        entity_id=f"entity:irsa_query:{uuid.uuid4()}",
        entity_type="query:irsa_sia",
        label=entity_label,
        attributes={
            "collection": collection,
            "release": release,
            "doi": doi,
            "cone_search": cone_search,
            "query_url": query_url,
            "product_count": product_count,
        },
    )
    a_query = W3CProvActivity(
        activity_id=f"activity:irsa_query:{uuid.uuid4()}",
        activity_type="query:irsa_sia",
        started_at=queried_at,
        ended_at=queried_at,
        used=[e_query.entity_id],
        attributes={
            "service": "NASA/IPAC IRSA SIA",
            "service_url": "https://irsa.ipac.caltech.edu/SIA",
        },
    )
    ag_irsa = W3CProvAgent(
        agent_id="agent:irsa",
        agent_type="service:irsa",
        label="NASA/IPAC Infrared Science Archive",
        attributes={"homepage": "https://irsa.ipac.caltech.edu"},
    )
    return provenance_service.record(
        entities=[e_query],
        activities=[a_query],
        agents=[ag_irsa],
        unified_object_id=unified_object_id,
        primary_role="primary",
    )


def make_jpl_horizons_provenance(
    *,
    target: str,
    epoch_utc: str,
    observer_location: str,
    query_url: str,
    queried_at: str,
    ra_deg: float,
    dec_deg: float,
    unified_object_id: Optional[str] = None,
) -> W3CProvBlock:
    """PROV-DM bundle for a successful JPL Horizons ephemeris."""
    e_ephem = W3CProvEntity(
        entity_id=f"entity:jpl_ephem:{uuid.uuid4()}",
        entity_type="ephemeris:jpl_horizons",
        label=f"Ephemeris for {target} at {epoch_utc}",
        attributes={
            "target": target,
            "epoch_utc": epoch_utc,
            "observer_location": observer_location,
            "ra_deg": ra_deg,
            "dec_deg": dec_deg,
        },
    )
    a_query = W3CProvActivity(
        activity_id=f"activity:jpl_query:{uuid.uuid4()}",
        activity_type="query:jpl_horizons",
        started_at=queried_at,
        ended_at=queried_at,
        used=[e_ephem.entity_id],
        attributes={
            "service": "NASA/JPL SSD Horizons API",
            "service_url": "https://ssd.jpl.nasa.gov/api/horizons.api",
            "query_url": query_url,
        },
    )
    ag_jpl = W3CProvAgent(
        agent_id="agent:jpl_horizons",
        agent_type="service:jpl_horizons",
        label="NASA/JPL Solar System Dynamics — Horizons",
        attributes={"homepage": "https://ssd.jpl.nasa.gov/horizons/"},
    )
    return provenance_service.record(
        entities=[e_ephem],
        activities=[a_query],
        agents=[ag_jpl],
        unified_object_id=unified_object_id,
        primary_role="primary",
    )


def make_bailer_jones_provenance(
    *,
    source_id: str,
    r_med_geo: Optional[float],
    r_lo_geo: Optional[float],
    r_hi_geo: Optional[float],
    r_med_photogeo: Optional[float],
    r_lo_photogeo: Optional[float],
    r_hi_photogeo: Optional[float],
    queried_at: str,
    unified_object_id: Optional[str] = None,
) -> W3CProvBlock:
    """PROV-DM bundle for a Bailer-Jones et al. (2021) posterior distance lookup.

    The asymmetric interval is preserved verbatim — never collapsed to ±sigma.
    """
    e_posterior = W3CProvEntity(
        entity_id=f"entity:bj_distance:{uuid.uuid4()}",
        entity_type="posterior:bailer_jones_distance",
        label=f"Distance posterior for Gaia DR3 {source_id}",
        attributes={
            "source_id": source_id,
            "r_med_geo": r_med_geo,
            "r_lo_geo": r_lo_geo,
            "r_hi_geo": r_hi_geo,
            "r_med_photogeo": r_med_photogeo,
            "r_lo_photogeo": r_lo_photogeo,
            "r_hi_photogeo": r_hi_photogeo,
            "doi": "10.3847/1538-3881/abd806",
        },
    )
    a_query = W3CProvActivity(
        activity_id=f"activity:bj_query:{uuid.uuid4()}",
        activity_type="query:gaia_bailer_jones_distance",
        started_at=queried_at,
        ended_at=queried_at,
        used=[e_posterior.entity_id],
        attributes={
            "service": "ESA Gaia Archive TAP",
            "tables": [
                "external.gaiadr3_geometric_distance",
                "external.gaiadr3_photogeometric_distance",
            ],
        },
    )
    ag_esa = W3CProvAgent(
        agent_id="agent:esa_gaia",
        agent_type="catalog:gaia_dr3",
        label="ESA Gaia DR3 + Bailer-Jones et al. 2021 posterior",
        attributes={
            "homepage": "https://gea.esac.esa.int/archive/",
            "reference": "Bailer-Jones et al. 2021, AJ 161, 147",
            "doi": "10.3847/1538-3881/abd806",
        },
    )
    return provenance_service.record(
        entities=[e_posterior],
        activities=[a_query],
        agents=[ag_esa],
        unified_object_id=unified_object_id,
        primary_role="primary",
    )


def make_kinematics_derivation_provenance(
    *,
    pmra_masyr: float,
    pmdec_masyr: float,
    parallax_mas: float,
    radial_velocity_kms: Optional[float],
    distance_pc: Optional[float],
    distance_method: str,
    tangential_velocity_kms: Optional[float],
    displacement_14yr_arcsec: float,
    derived_at: str,
    unified_object_id: Optional[str] = None,
    upstream_entity_ids: Optional[List[str]] = None,
) -> W3CProvBlock:
    """PROV-DM bundle for derived kinematics (tangential velocity, displacement).

    Records the propagation formula in the activity attributes and references
    the upstream entities that fed the derivation.
    """
    e_derived = W3CProvEntity(
        entity_id=f"entity:kinematics:{uuid.uuid4()}",
        entity_type="derivation:kinematics",
        label="Tangential velocity and displacement from Gaia astrometry",
        attributes={
            "pmra_masyr": pmra_masyr,
            "pmdec_masyr": pmdec_masyr,
            "parallax_mas": parallax_mas,
            "radial_velocity_kms": radial_velocity_kms,
            "distance_pc": distance_pc,
            "distance_method": distance_method,
            "tangential_velocity_kms": tangential_velocity_kms,
            "displacement_14yr_arcsec": displacement_14yr_arcsec,
        },
    )
    a_derive = W3CProvActivity(
        activity_id=f"activity:kinematics_derive:{uuid.uuid4()}",
        activity_type="derivation:kinematics",
        started_at=derived_at,
        ended_at=derived_at,
        used=upstream_entity_ids or [],
        attributes={
            "propagation_formula": (
                "v_tan = 4.74 * sqrt(pmra^2 + pmdec^2) / parallax_mas   [km/s, mas/yr, mas]"
            ),
            "displacement_formula": "d(theta) = sqrt(pmra^2 + pmdec^2) * delta_t",
            "delta_t_yr": 14.2,
        },
    )
    ag_odyssey = W3CProvAgent(
        agent_id="agent:odyssey_kinematics",
        agent_type="service:odyssey",
        label="SPHEREx Odyssey Kinematics Engine",
        attributes={"component": "adapters/normalization.py:build_unified_object"},
    )
    return provenance_service.record(
        entities=[e_derived],
        activities=[a_derive],
        agents=[ag_odyssey],
        unified_object_id=unified_object_id,
        primary_role="derived",
    )


def build_provenance_bundle(
    *,
    service: str,
    endpoint: str,
    adapter_contract: str,
    extra: Optional[Dict[str, Any]] = None,
    primary_role: str = "primary",
) -> Dict[str, Any]:
    """Generic W3C PROV-DM provenance bundle builder for external catalog/service queries."""
    extra_dict = extra or {}
    now_iso = datetime.now(timezone.utc).isoformat()
    u_id = uuid.uuid4()
    entity_id = f"entity:service_result:{u_id}"
    activity_id = f"activity:query:{u_id}"
    agent_id = f"agent:{uuid.uuid4()}"

    e_result = W3CProvEntity(
        entity_id=entity_id,
        entity_type="service:query_result",
        label=f"Query result from {service}",
        attributes=extra_dict,
    )
    a_query = W3CProvActivity(
        activity_id=activity_id,
        activity_type="query:external_service",
        started_at=now_iso,
        ended_at=now_iso,
        used=[entity_id],
        attributes={
            "endpoint": endpoint,
            "adapter_contract": adapter_contract,
        },
    )
    ag_service = W3CProvAgent(
        agent_id=agent_id,
        agent_type="service:upstream",
        label=service,
        attributes={"service": service, "endpoint": endpoint},
    )
    bundle = provenance_service.record(
        entities=[e_result],
        activities=[a_query],
        agents=[ag_service],
        primary_role=primary_role,
    )
    return {
        "service": service,
        "endpoint": endpoint,
        "adapter_contract": adapter_contract,
        "generated_at": now_iso,
        "bundle_id": bundle.bundle_id,
        "w3c_bundle": bundle.model_dump(),
        **extra_dict,
    }

